# Generated by Django 4.0.3 on 2022-03-24 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_endTime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_startTime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
