# Generated by Django 4.0.3 on 2022-03-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_session_session_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
