# Generated by Django 4.0.3 on 2022-04-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_profile_id'),
        ('mainapp', '0005_delete_session'),
    ]

    operations = [
    ]
